spring.application.name=ct5209-springboot-war

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

otel.traces.exporter=otlp
otel.metrics.exporter=none
otel.logs.exporter=none
otel.exporter.otlp.protocol=http/protobuf
otel.exporter.otlp.traces.endpoint=http://localhost:4318/v1/traces
otel.traces.sampler=always_on